all:
	pdflatex libddg_userguide
	bibtex libddg_userguide
	pdflatex libddg_userguide
	open libddg_userguide.pdf

clean:
	rm -f libddg_userguide.aux
	rm -f libddg_userguide.bbl
	rm -f libddg_userguide.blg
	rm -f libddg_userguide.log
	rm -f libddg_userguide.out
	rm -f libddg_userguide.toc

